#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for CMUDB core code changes
#
# IDENTIFICATION
#    src/backend/cmudb/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/cmudb
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = qss

include $(top_srcdir)/src/backend/common.mk
