#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for qss
#
# IDENTIFICATION
#    src/backend/cmudb/qss/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/cmudb/qss
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qss.o

include $(top_srcdir)/src/backend/common.mk
