#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for tscout
#
# IDENTIFICATION
#    src/backend/tscout/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/tscout
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	sampling.o

include $(top_srcdir)/src/backend/common.mk
